### ISSUE TITLE
EKS Fargate pods with storage needs delay to start a pod

### ISSUE THREAD

**Issue by NEwa-05** [traefik/traefikee-helm-chart#127]
Description:

When deploying a pod with storage in an EKS Fargate cluster, the pod will not start because pv/pvc needs to be bound before it starts as described in this [article](https://repost.aws/articles/ARvp6j-8c4Q4W9Zg7Zw3o_4g/demystifying-efs-claim-not-bound-on-aws-fargate-with-amazon-eks).

Issue:

When deploying Traefik Enterprise with the Helm chart both controller and registry will be in pending mode until K8s loop and restart (nearly 1hr), when deploying for the first time user will need to rollout restart the stateful set just after deploying.

**Comment by mloiseleur** [comment]
Following FarGate current limitations, I understand that the PVC needs to created first, with the expected name, before installing with the Chart.

**Comment by NEwa-05** [comment]
Yes, I did test it out with a quick and dirty change on the chart, and creating PV and PVC before the statefulset did the trick.

The stateful pods can start immediately by creating the PV and the PVC before the statefulset in the chart (removing the volumeClaimTemplates part).

**Comment by NEwa-05** [comment]
Will retry Monday for a full deployment with the volumeClaimTemplates and adapt my pv YAML accordingly.

**Comment by mloiseleur** [comment]
@NEwa-05 Anything left to do on this issue ?

**Comment by NEwa-05** [comment]
Yes, sorry, I'll close this issue, the documentation will have an EKS Fargate annotation to cover this need.
Thanks.
